Measure connection latency
lbbrhzn/ocpp pull request #317
Opened 2022-01-20 20:03 UTC by lbbrhzn

2022-01-20 20:18 UTC, drc38 requested changes
Looks good, if you add the measurement state class then statistics over time can be generated to see how stable the latency is

2022-01-20 20:23 UTC, lbbrhzn commented
> Looks good, if you add the measurement state class then statistics over time can be generated to see how stable the latency is

i'll do, thanks!

2022-01-20 22:21 UTC, lbbrhzn commented
Hmm, what SensorDeviceClass should I use? There is only timestamp, no timedelta.

2022-01-20 22:24 UTC, drc38 commented
> Hmm, what SensorDeviceClass should I use? There is only timestamp, no timedelta.

Does it need one? Set to None?

2022-01-22 10:43 UTC, drc38 commented on custom_components/ocpp/api.py
> +                _LOGGER.info(
suggest changing this to debug or commenting out before merging

2022-01-22 10:53 UTC, drc38 commented on custom_components/ocpp/api.py
> +                pong_waiter = await self._connection.ping()
use asyncio.wait_for(self._connection.ping(), timeout=20) to ensure the loop does not get stuck if there is no response to the ping

2022-01-22 15:32 UTC, merged