improve reconnect and trigger boot notification
lbbrhzn/ocpp pull request #341
Opened 2022-01-31 22:54 UTC by lbbrhzn

2022-01-31 23:57 UTC, drc38 reviewed
Should there be a `finally:`  before line 821?

2022-02-01 06:36 UTC, drc38 commented
I think you also need to set `return_exceptions=True` on gather and then cancel the gather on exception to stop the monitor_connection task in the `start` and `reconnect` try blocks.

2022-02-01 17:31 UTC, lbbrhzn commented
yes, something like that is needed. But I've read somewhere that cancelling  gather does not automatically cancel the underlying tasks. So you need to do something like this:
https://python.tutorialink.com/how-to-cancel-all-remaining-tasks-in-gather-if-one-fails/

2022-02-01 18:22 UTC, drc38 commented
My understanding is if return_exceptions is True then cancelling gather will cancel the other tasks, but I haven't confirmed with a piece of test code. The difference being you have to test the result for an Exception. https://hynek.me/articles/waiting-in-asyncio/

2022-02-01 20:19 UTC, drc38 commented
> My understanding is if return_exceptions is True then cancelling gather will cancel the other tasks, but I haven't confirmed with a piece of test code. The difference being you have to test the result for an Exception. https://hynek.me/articles/waiting-in-asyncio/

Ignore this, you are right it will only work for finite tasks as the result from gather is only returned after all tasks have completed successfully or thrown an exception (which may happen but there is no guarantee).  I agree option 2 looks cleaner.

2022-02-01 21:10 UTC, drc38 commented
Another option worth considering is removing the closing from the monitor_connection function, and simply propagate the error back to the calling try block (start and reconnect), after which the connection will close in the finally statement. The logging and closing can then be handled there eg

In monitor_connection:
```
except Exception as e:
    raise e
```

In start/reconnect:
```
except asyncio.TimeoutError:
            _LOGGER.debug(f"Timeout in connection '{self.id}'")
        except websockets.exceptions.ConnectionClosed as connection_closed_exception:
            _LOGGER.debug(
                f"Connection closed to '{self.id}': {connection_closed_exception}"
            )
        except Exception as other_exception:
            _LOGGER.error(
                f"Unexpected exception in connection to '{self.id}': {other_exception}",
                exc_info=True,
            )
```

2022-02-01 23:26 UTC, lbbrhzn commented
got something that seems to work now, please review.

2022-02-01 23:44 UTC, drc38 requested changes
I'm getting the following error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/websockets/legacy/server.py", line 293, in handler
    await self.ws_handler(self, path)
  File "/config/custom_components/ocpp/api.py", line 203, in on_connect
    f"Charger {cp_id} disconnected from {self.host}:{self.port} websocket={websocket.id}."
AttributeError: 'WebSocketServerProtocol' object has no attribute 'id'
```

2022-02-01 23:52 UTC, lbbrhzn commented
Strange, works for me. What is your websockets version?

2022-02-02 00:02 UTC, lbbrhzn commented
i'll release as beta now, so others can check if it works

2022-02-02 00:02 UTC, merged

2022-02-02 00:38 UTC, drc38 commented
> Strange, works for me. What is your websockets version? Should be there, see https://websockets.readthedocs.io/en/stable/reference/server.html#websockets.server.WebSocketServerProtocol

That's odd somehow HA reverted to websockets 9.1 although I have been on 10.1 for sometime... I had to go into bash and upgrade to get 10.1 back again. This may be the reason:
```
volvooncall 0.9.1 requires websockets<=8.1, but you'll have websockets 10.1 which is incompatible.
vallox-websocket-api 2.8.1 requires websockets<10.0,>=9.1, but you'll have websockets 10.1 which is incompatible.
```