Added detection between session and main meter energy values
lbbrhzn/ocpp pull request #919
Opened 2023-09-26 12:19 UTC by nlindn

Added detection between session and main meter energy values as discussed in #366.

According to OCPP spec, if there is a transaction id the values are for that session and if there is no transaction id the values are from main meter. For example ABB Terra AC sends separate energy used for the session and the charger lifetime energy usage.

Now if there is a transaction id with the energy value, it is saved to entity "xxx.Session" (example: "Energy.Active.Import.Register.Session")

If there is no transaction id with the energy value, it is saved to entity "xxx" (example: ""Energy.Active.Import.Register)

This way the energy values between the sessions and main meters are kept separated so that they don't mix in the homeassistant history and graphs. Also, if the charger gives the energy used in the session it is not calculated duplicated.

2023-09-26 18:18 UTC, drc38 commented
Thanks, I take it ABB have not released a new firmware to conform to 3.9 of the errata then? 
https://github.com/mobilityhouse/ocpp/blob/master/docs/v16/ocpp-1.6-errata-sheet.pdf

2023-09-26 19:52 UTC, nlindn commented
> Thanks, I take it ABB have not released a new firmware to conform to 3.9 of the errata then? https://github.com/mobilityhouse/ocpp/blob/master/docs/v16/ocpp-1.6-errata-sheet.pdf

Yeah, the spec 3.9 is not implemented yet in Terra AC. The Sample.Periodic response has the session energy started from 0 for every session.

`receive message [2, "2503015", "MeterValues", 
	{"connectorId": 1, "transactionId": 1695585075, "meterValue": 
		[{"timestamp": "2023-09-24T21:40:03.000Z", "sampledValue": 
			[{.................................,
			{"value": "1868", "context": "Sample.Periodic", "format": "Raw", "measurand": "Energy.Active.Import.Register", "unit": "Wh"},
			..................................}]
		}]
	}
]`

And the Sample.Clock sends the main meter values.

`receive message [2, "2778188", "MeterValues",
	{"connectorId": 1, "meterValue": 
		[{"timestamp": "2023-09-24T21:45:00.000Z", "sampledValue": 
			[{"value": "927435", "context": "Sample.Clock", "format": "Raw", "measurand": "Energy.Active.Import.Register", "location": "Inlet"}]}]}]`

If other chargers on the market are sending the main meter value not starting from 0 as suggested in the 3.9 of the errata. Then the default assumption in this pull request implementation is maybe not the best. Do we want the default assumption to be that the energy values does not start from zero for transactions and if 3.9 of the errata is not yet implemented, then do some workarounds to stop the mixing of values that is happening now?

2023-09-26 20:07 UTC, drc38 commented
>If other chargers on the market are sending the main meter value not starting from 0 as suggested in the 3.9 of the errata. Then the default assumption in this pull request implementation is maybe not the best. Do we want the default assumption to be that the energy values does not start from zero for transactions and if 3.9 of the errata is not yet implemented, then do some workarounds to stop the mixing of values that is happening now?

That would be better, it seems to only be the ABB units with the issue. Also any reason to change from `Energy.Session` as it will break any reporting users have setup etc?

2023-09-28 13:15 UTC, nlindn commented
> That would be better, it seems to only be the ABB units with the issue. Also any reason to change from `Energy.Session` as it will break any reporting users have setup etc?

Changed the logic of the fix as discussed and kept the entitie names unchanged to avoid breaking setups.

2023-09-29 00:01 UTC, drc38 commented
@nlindn we shouldn't need to maintain a list of charger models in the integration that do not support errata 3.9. Can you rework to remove that requirement please.

2023-09-29 00:04 UTC, drc38 commented
Why did you drop the test case in the latest commits?

2023-10-02 19:54 UTC, nlindn commented
> @nlindn we shouldn't need to maintain a list of charger models in the integration that do not support errata 3.9. Can you rework to remove that requirement please.

From the meterStart value on startTransaction it can be detected if the errata 3.9 is fulfilled or not. Problem is that if homeassistant is restarted during a charging session the meterStart value is not available after the reboot for the still ongoing session. Any ideas for a good solution for getting the meterStart value for ongoing session if startTransaction is missed?

2023-10-03 10:43 UTC, drc38 commented
> > @nlindn we shouldn't need to maintain a list of charger models in the integration that do not support errata 3.9. Can you rework to remove that requirement please.
> 
> From the meterStart value on startTransaction it can be detected if the errata 3.9 is fulfilled or not. Problem is that if homeassistant is restarted during a charging session the meterStart value is not available after the reboot for the still ongoing session. Any ideas for a good solution for getting the meterStart value for ongoing session if startTransaction is missed?

It should be fairly rare for a HA restart to occur during a charge session. I wouldn't worry about it.

2023-10-05 19:09 UTC, drc38 commented
Great work 🙏.  Please add `jsonschema==4.19.0` to requirements_dev.txt as I suspect that is a reason for the tests not running. Cheers

2023-10-05 20:12 UTC, drc38 requested changes

2023-10-05 20:12 UTC, drc38 commented on tests/test_charge_point.py
> +                    cp.send_start_transaction_meter_start_zero(),
Lines 330 to 336 are not required as they've already been tested

2023-10-05 20:12 UTC, drc38 commented on tests/test_charge_point.py
> +                    cp.send_meter_periodic_data(),
Same with 338-339, this is slowing test and causing timeout

2023-10-05 21:31 UTC, nlindn commented
Removed duplicated tests. Timeout of 30sec was still not enough so increased the timeout for test_cms_responses in test_charge_point.py to 60sec.

2023-10-05 21:55 UTC, drc38 commented
> Removed duplicated tests. Timeout of 30sec was still not enough so increased the timeout for test_cms_responses in test_charge_point.py to 60sec.

Nice one, just linting to fix and take a look at codecov report to see if you can increase test coverage.

2023-10-06 18:49 UTC, drc38 approved these changes

2023-10-06 18:51 UTC, merged

2023-10-09 06:18 UTC, drc38 commented
@nlindn, testing the changes on my unit and it breaks the logic for a normal charger
![image](https://github.com/lbbrhzn/ocpp/assets/20024196/ada5987f-3d8f-4ca3-9da5-c602243a7efb)

Please review

2023-10-09 07:11 UTC, drc38 commented on custom_components/ocpp/api.py
> +                                float(value) / 1000
@nlindn this should only be /1000 if unit == DEFAULT_ENERGY_UNIT

2023-10-09 07:14 UTC, drc38 commented on custom_components/ocpp/api.py
>                              self._metrics[measurand].unit = HA_ENERGY_UNIT
Same applies here

2023-10-09 10:04 UTC, drc38 commented on tests/test_charge_point.py
adding `assert float(cs.get_metric("test_cpid", "Energy.Active.Import.Register")) == float(
        1101.452
    )` here will show error with current code

2023-10-09 17:54 UTC, nlindn commented
> @nlindn, testing the changes on my unit and it breaks the logic for a normal charger

Yeah, the logic has some bugs that passed the tests but reports values wrong on errata 3.9 chargers.  Should I open a new pr for fixes or what is the best way to do it?

2023-10-09 17:55 UTC, drc38 commented
Open a new PR